### ISSUE TITLE
Search yields no results

### ISSUE THREAD

**Issue by deining** [hugomods/search#128]
I followed the instructions in your recent [blog post](https://hugomods.com/en/blog/2023/05/integrate-docsy-with-the-search-module/) about setting up the search with docsy theme.

**Observations:**

* After setting up the search, there are a lot of warnings, all of the same kind:
```
WARN 2023/05/06 21:44:16 found no layout file for "searchindex" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2023/05/06 21:44:16 found no layout file for "searchindex" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
...
```

Any way to avoid these annoying warnings?

**More important:** I followed the instructions in your blog post. Once finished, I started up hugo server. Site preview of the original docsy example site is fine. I can invoke your modal search via `CTRL-K`. When typing in a search expression, I don't see any results, regardless of the input. Any idea what's wrong here? Any way to debug this further or how to get more insight on what is going wrong here? Your help is appreciated.

**Comment by razonyang** [comment]
I guess you're appending `SearchIndex` on `section` output instead of `home` output.

**Comment by deining** [comment]
> I guess you're appending `SearchIndex` on `section` output instead of `home` output, move the `SearchIndex` to the `home` output should work.

Bingo. It now works like a charm!

Reflecting on my experience: your blog post helped to get me started, but it is really terse (too terse for me :wink:).
What about adding your search options to the section [navigation and search](https://www.docsy.dev/docs/adding-content/navigation/) of the docsy user guide? If you start a pull request (taking your blog post as base point), I'm willing to co-author and extend the points that were unclear/difficult to grasp for me.

**Comment by razonyang** [comment]
> What about adding the search you developed to the section [navigation and search](https://www.docsy.dev/docs/adding-content/navigation/) of the docsy user guide?

Sounds good, but the guide assumes either GCS or offline search to be enabled, needs to be improved to get rid of this and shows the shortcut if set. Will create a PR once it's done.
