### ISSUE TITLE
How to build and run the exampleSite locally ? trying with npm ci and hugo server doesn't work.

### ISSUE THREAD

**Issue by techhubhub** [hugomods/search#203]
How to build and run the exampleSite locally ? trying with npm ci and hugo server doesn't work.
also, how does this search compare to https://github.com/hbstack/search ? 
let's say we would like to use one of the search as mod, which one you recommend  ?
Thank you.

**Comment by razonyang** [comment]
> How to build and run the exampleSite locally?

```sh
git clone https://github.com/hugomods/search.git hugomods-search

cd hugomods-search/exampleSite

npm ci

hugo server
```

And then navigate to http://localhost:1313, and type _Hugo_ to search.

> How does this search compare to https://github.com/hbstack/search?

`github.com/hbstack/search` is an _adapter_ that integrated `github.com/hugomods/search` into HB Framework.
HB Framework themes already integrated this module, for example.

- https://theme.hbstack.dev/
- https://theme-cards.hbstack.dev/

If you want to integrate this search module into your theme, see also:

- https://hugomods.com/search/ 
- [Integrate Docsy With the Search Module](https://hugomods.com/blog/2023/05/integrate-docsy-with-the-search-module/)

**Comment by razonyang** [comment]
> Any update on this feature request ? https://github.com/hugomods/search/issues/164

Not yet, you can subscribe that issue until it's done. If I understand the request correctly, you wish _search_ without keywords?
