### ISSUE TITLE
feature request : Can you build the example page as this ?

### ISSUE THREAD

**Issue by techhubhub** [hugomods/search#212]
Can you build the example page as this 
<img width="1238" alt="image" src="https://github.com/hugomods/search/assets/158099291/4dc9c5cc-a5e5-4b7b-8810-46b172619e43">
(picture 1)

instead of 

<img width="806" alt="image" src="https://github.com/hugomods/search/assets/158099291/59bf9580-9367-41a3-93a2-f3ef466630a7">
(picture 2)
notice that if we visit http://localhost:1313/search (http://localhost:1313/search/?q=) will display the picture 1
so we can only set baseURL as http://domain.ltd/search to achieve this ? 
Best

**Comment by razonyang** [comment]
Hmm, I didn't get it, there are two modes of this module:

 1. [Single search page](https://hugomods.com/search/single-page/): standalone page to search and display results, in this way, users have to open the search page.
 1. [Modal](https://hugomods.com/search/modal/): pops up a search box on current page.

The example include both of them, just tweak it to suit your needs.

**Comment by techhubhub** [comment]
I was trying to edit the config, where it displays all the blogs below the search input box without any string. then I was able to use filters to narrow down my the search. ( not sure if was Single search page or Modal)  but I think it was a good UI and UX

**Comment by razonyang** [comment]
> where it displays all the blogs below the search input box without any string. 

I think this has been fixed, should be empty result if no filters (keywords and taxonomies) applied.

**Comment by razonyang** [comment]
> I actually like that as feature. ( and I have been trying to achieve that display for hours)

This won't be accepted, histories should be shown if no filters.

> How can we set baseUrl/default url as .com/search ?

If you're talking the example site, it's dynamic, just specify the right `baseURL`, in your case `https://as.com`, when you deploy site in production mode, then the search url will be `as .com/search`.

See https://github.com/hugomods/search/blob/d5733092d96c5ae395a9576ccc81d2b50d393806/exampleSite/layouts/partials/alerts.html#L12-L13

**Comment by techhubhub** [comment]
so we can put 
`baseUrl=https://as.com `
 in hugo.toml  file ?

**Comment by razonyang** [comment]
yes
