### ISSUE TITLE
Add configuration for disabling search history

### ISSUE THREAD

**Issue by nicokaiser** [hugomods/search#216]
After updating to v0.11 there is a new search history feature. While this is really nice, it might be required to completely disable this feature in some cases. In some environments it might not be desirable to save data in localStorage etc.

Setting the `histories_count` parameter to `0` does not help, since then the default (`5`) is applied. Setting the parameter to `"0"` (with quotes!) basically disables the history, but this is more like a hack to the problem.

**Comment by razonyang** [comment]
Make sense, available since v0.12.0.

```yaml
params:
  search:
    histories: false
```

**Comment by nicokaiser** [comment]
Awesome, thank you!
