### ISSUE TITLE
Feature Request: please add the option to clear all filters with one click.

### ISSUE THREAD

**Issue by creditket** [hugomods/search#219]
<img width="1253" alt="image" src="https://github.com/hugomods/search/assets/93809455/a22561db-8ffb-4273-b21f-c39f36f805c9">
Maybe in front of English Or at the end of  Expand ? Thank you.

**Comment by razonyang** [comment]
I think it would be better to use the _reset_ button.

![image](https://github.com/hugomods/search/assets/17720932/212c7c65-1cb1-43a7-b2db-0d12b283a946)

**Comment by creditket** [comment]
<img width="1227" alt="image" src="https://github.com/hugomods/search/assets/93809455/07a7bd86-59ab-47e5-962c-71e32d85c3ba">
When only filters are chosen, the reset is not available.

**Comment by razonyang** [comment]
Not implement yet, just saying using the reset button would be better.

**Comment by razonyang** [comment]
Available since v0.13.0
